# 10 minutes to pandas

https://pandas.pydata.org/docs/user_guide/10min.html

In [2]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1,2,3,4,5])
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [5]:
s.mean()

np.float64(3.0)

In [6]:
s.median()

np.float64(3.0)

In [7]:
s.mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

## Examples of Degrees of Freedom

### Example 1 : n - 1
- Consider a data sample consisting of five positive integers
- The values of the five integers must have an average of six
- If four items within the data set are {3, 8, 5, and 4}, the fifth number must be 10
- Because the first four numbers can be chosen at random, the degree of freedom is four

### Example 2 : n OR n - 0
- Consider a data sample consisting of five positive integers
- The values could be any number with no known relationship between them
- In other words, there are no constraints and limitations on the numbers selected
- Because all five numbers can be selected randomly and with no limitations, the degree of freedom is five

In [59]:
example_one = pd.Series([3,4,5,8,10])
example_one.mean()

np.float64(6.0)

In [60]:
ra = np.sum(example_one[:]) / len(example_one)
ra == example_one.mean()

np.True_

In [61]:
first_four = example_one[:-1]
first_four

0    3
1    4
2    5
3    8
dtype: int64

In [62]:

rb = np.sum(first_four) / len(example_one)

In [63]:
missing_value = (ra - rb) * len(example_one)
missing_value == 10

np.True_

## Population Standard Deviation
- When calculating the standard deviation for an entire population, there are no restrictions on the data points, so the divisor is N (the total number of elements)
- In this case, ddof = 0, so the divisor is N - 0 = N.
- Default for NumPy

In [64]:
# pandas >> population standard deviation : n
# ddof : int, default 1
# Delta Degrees of Freedom
# The divisor used in calculations is N - ddof, where N represents the number of elements
s.std(ddof=0)

np.float64(1.4142135623730951)

In [65]:
# numpy >> population standard deviation : n
# ddof : int, float, default 0
np.std(s)

np.float64(1.4142135623730951)

## Sample Standard Deviation
- When calculating standard deviation for a sample, the sample mean is usually used as an intermediate parameter
- This is a restriction because the last data point is no longer free to vary once the mean is set
- The sample size is reduced by one to account for this restriction, making the divisor N - 1
- In this case, ddof = 1
- Default for pandas

In [66]:
# pandas >> sample standard deviation : n - 1
# ddof : int, default 1
# Delta Degrees of Freedom
# The divisor used in calculations is N - ddof, where N represents the number of elements
s.std()

np.float64(1.5811388300841898)

In [67]:
# numpy >> sample standard deviation : n - 1
# ddof : int, float, default 0
np.std(s, ddof=1)

np.float64(1.5811388300841898)

In [68]:
a = s[0] - s.mean()
b = s[1] - s.mean()
c = s[2] - s.mean()
d = s[3] - s.mean()
e = s[4] - s.mean()

total = (a ** 2) + (b ** 2) + (c ** 2) + (d ** 2) + (e ** 2)

In [69]:
# population standard deviation : n << numpy
population = total / len(s)
psd = np.sqrt(population)
psd

np.float64(1.4142135623730951)

In [70]:
# sample standard deviation : n - 1 << pandas
sample = total / (len(s) - 1)
ssd = np.sqrt(sample)
ssd

np.float64(1.5811388300841898)

In [71]:
dates = pd.date_range(start='2018-01-01', end='2018-12-31')
dates

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25',
               '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29',
               '2018-12-30', '2018-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [72]:
dfDates = pd.DataFrame(dates)
dfDates

             0
0   2018-01-01
1   2018-01-02
2   2018-01-03
3   2018-01-04
4   2018-01-05
..         ...
360 2018-12-27
361 2018-12-28
362 2018-12-29
363 2018-12-30
364 2018-12-31

[365 rows x 1 columns]

In [73]:
numDates = 4
numRandoms = 7

cols = [chr(x) for x in list(range(97, 97 + numRandoms))]

moreDates = pd.date_range("20130101", periods=numDates)
dfRandomDates = pd.DataFrame(np.random.randn(numDates, numRandoms), index=moreDates, columns=cols)
dfRandomDates

,a,b,c,d,e,f,g
2013-01-01,2.713731,0.112712,0.879175,-0.484324,-0.625243,0.174148,0.551810
2013-01-02,1.898830,-2.993448,-1.783326,-0.111565,1.777970,-0.648635,-0.941194
2013-01-03,-1.667471,-0.708501,-1.015580,-0.062853,-0.715187,-0.595935,0.350762
2013-01-04,1.425317,-0.441228,0.285669,-0.276201,-1.588591,-0.051358,2.298520

In [74]:
ll = list(range(97, 97 + numRandoms))
ll

[97, 98, 99, 100, 101, 102, 103]

In [75]:
def characters(char, count):
    s = ''
    for x in range(count):
        s += chr(char + x)
    return s

In [76]:
kk = [characters(x, 20) for x in ll]
kk

['abcdefghijklmnopqrst',
 'bcdefghijklmnopqrstu',
 'cdefghijklmnopqrstuv',
 'defghijklmnopqrstuvw',
 'efghijklmnopqrstuvwx',
 'fghijklmnopqrstuvwxy',
 'ghijklmnopqrstuvwxyz']