# Intro to Machine Learning

## Home Data

In [66]:
import pandas as pd

In [67]:
home_data = pd.read_csv('./data/home-data-train.csv')

In [68]:
home_data.shape

(1460, 81)

In [69]:
home_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [70]:
average_lot_size = home_data['LotArea'].mean()
average_lot_size

np.float64(10516.828082191782)

In [71]:
newest_home_age = 2025 - home_data['YearBuilt'].max()
newest_home_age

np.int64(15)

## Prediction Target, y

In [72]:
y = home_data.SalePrice

In [73]:
type(y)

pandas.core.series.Series

In [74]:
y.head().to_list()

[208500, 181500, 223500, 140000, 250000]

In [75]:
y.mean(), y.median()

(np.float64(180921.19589041095), np.float64(163000.0))

In [76]:
y.mode()

0    140000
Name: SalePrice, dtype: int64

In [77]:
type(y.mode())

pandas.core.series.Series

In [78]:
y.mode().iloc[0]

np.int64(140000)

In [79]:
int(y.mean()), int(y.median()), int(y.mode().iloc[0])

(180921, 163000, 140000)

## Predictive Features, X

In [80]:
feature_names = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]
X = home_data[feature_names]

In [81]:
type(X)

pandas.core.frame.DataFrame

In [82]:
X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

In [83]:
X.describe()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1971.267808,1162.626712,346.992466,1.565068,2.866438,6.517808
std,9981.264932,30.202904,386.587738,436.528436,0.550916,0.815778,1.625393
min,1300.000000,1872.000000,334.000000,0.000000,0.000000,0.000000,2.000000
25%,7553.500000,1954.000000,882.000000,0.000000,1.000000,2.000000,5.000000
50%,9478.500000,1973.000000,1087.000000,0.000000,2.000000,3.000000,6.000000
75%,11601.500000,2000.000000,1391.250000,728.000000,2.000000,3.000000,7.000000
max,215245.000000,2010.000000,4692.000000,2065.000000,3.000000,8.000000,14.000000

## Specify and Fit Model

### Define

- y (target)
- X (features)
- model (DecisionTreeRegressor)

### Fit

- `model.fit(X, y)`

### DecisionTreeRegressor


`Decision Trees (DTs)`
- are a `non-parametric supervised learning` method used for classification and regression
- the goal is to create a model that predicts the `value` of a target variable by learning simple decision rules inferred from the data `features`
- a tree can be seen as a `piecewise constant approximation`

`Non parametric`
- refers to statistical methods and tests that make minimal or no assumptions about the shape of the data's underlying population distribution

`Supervised learning`
- is a category of machine learning that uses labeled datasets to train algorithms to predict outcomes and recognize patterns

`Piecewise constant approximation`
- is a method to represent a continuous function or signal by a series of distinct, constant-value steps or rectangles, typically over a partition of the domain
- this approach simplifies complex data by breaking it into smaller, manageable segments, with each segment having a single, constant value

`Docs`
- https://scikit-learn.org/stable/modules/tree.html#decision-trees
- https://scikit-learn.org/stable/modules/tree.html#regression
- https://scikit-learn.org/stable/auto_examples/tree/plot_tree_regression.html#decision-tree-regression
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html

In [84]:
from sklearn.tree import DecisionTreeRegressor

In [85]:
iowa_model = DecisionTreeRegressor(random_state=1)

In [86]:
type(iowa_model)

sklearn.tree._classes.DecisionTreeRegressor

In [87]:
iowa_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

## Make Predictions

### Predict
- `model.predict(X)`

In [88]:
predictions = iowa_model.predict(X)
predictions

array([208500., 181500., 223500., ..., 266500., 142125., 147500.],
      shape=(1460,))

## Model Validation

### Evaluate

- determine how accurate the model's predictions are

In [89]:
print("First in-sample predictions:", iowa_model.predict(X.head()))
print("Actual target values for those homes:", y.head().tolist())

First in-sample predictions: [208500. 181500. 223500. 140000. 250000.]
Actual target values for those homes: [208500, 181500, 223500, 140000, 250000]

### The Problem with "In-Sample" Scores

- the measure we just computed can be called an "in-sample" score
- we used a single "sample" of houses for both building the model and evaluating it
- models' practical value come from making predictions on new data
- we measure performance on data that wasn't used to build the model

### Validation Data

- exclude some data from the model-building process
- test the model's accuracy on data it has not seen before

### Train Test Split
- `train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)`

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)

In [92]:
iowa_model_split = DecisionTreeRegressor(random_state=1)

In [93]:
type(iowa_model_split)

sklearn.tree._classes.DecisionTreeRegressor

In [94]:
iowa_model_split.fit(train_X, train_y)

DecisionTreeRegressor(random_state=1)

In [95]:
val_predictions = iowa_model_split.predict(val_X)

In [96]:
print("Validation predictions:", val_predictions[:5])
print("Validation prices:", val_y.head().tolist())

Validation predictions: [186500. 184000. 130000.  92000. 164500.]
Validation prices: [231500, 179500, 122000, 84500, 142000]

### Mean Absolute Error

- `val_mae = mean_absolute_error(val_y, val_predictions)`

In [97]:
from sklearn.metrics import mean_absolute_error
val_mae = mean_absolute_error(val_y, val_predictions)

In [98]:
print("Validation MAE: {:,.0f}".format(val_mae))

Validation MAE: 29,653

In [99]:
def get_mae(max_leaf_nodes, train_features_x, val_features_x, train_target_y, val_target_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_features_x, train_target_y)
    predictions_val = model.predict(val_features_x)
    mae = mean_absolute_error(val_target_y, predictions_val)
    return mae

print("get_mae complete")

get_mae complete

In [100]:
candidate_max_leaf_nodes = [5, 25, 50, 100, 250, 500]
scores = {leaf_size: get_mae(leaf_size, train_X, val_X, train_y, val_y) for leaf_size in candidate_max_leaf_nodes}
print(scores)

{5: 35044.51299744237, 25: 29016.41319191076, 50: 27405.930473214907, 100: 27282.50803885739, 250: 27893.822225701646, 500: 29454.18598068598}

In [101]:
best_tree_size = min(scores, key=scores.get)
print("best_tree_size: {:,.0f}\nmax_leaf_nodes: {:,.0f}".format(best_tree_size, scores[best_tree_size]))

best_tree_size: 100
max_leaf_nodes: 27,283

In [102]:
candidate_max_leaf_nodes_plus = [n for n in range(50, 100)]
scores_plus = {leaf_size: get_mae(leaf_size, train_X, val_X, train_y, val_y) for leaf_size in candidate_max_leaf_nodes_plus}
print(scores_plus)

{50: 27405.930473214907, 51: 27609.18709421947, 52: 27608.423395589336, 53: 27683.23178081142, 54: 27650.059178071693, 55: 27662.52507381978, 56: 27673.07883809908, 57: 27611.17044610751, 58: 27398.984429339976, 59: 27308.306384378084, 60: 27110.899339368298, 61: 27076.71826354303, 62: 26989.920001470247, 63: 26976.609928948084, 64: 26926.94435817183, 65: 27044.389659920456, 66: 26985.01149040254, 67: 26985.01149040254, 68: 26943.66809417612, 69: 26759.46382428237, 70: 26763.340028993345, 71: 26704.033546536175, 72: 26847.869162974534, 73: 27044.086130049753, 74: 27156.990239638795, 75: 27114.12284949469, 76: 27104.860618574927, 77: 27298.072186307043, 78: 27220.54904396041, 79: 27155.08343092544, 80: 27389.89243288238, 81: 27389.89243288238, 82: 27569.91370215911, 83: 27585.32010147087, 84: 27670.694743555534, 85: 27536.423432400934, 86: 27366.760027312874, 87: 27432.843393261992, 88: 27432.843393261992, 89: 27432.843393261992, 90: 27411.5488346623, 91: 27411.5488346623, 92: 27245.097160385278, 93: 27151.7344891524, 94: 27243.74005052764, 95: 27268.728164951488, 96: 27321.220744860162, 97: 27179.26010402966, 98: 27236.223802659802, 99: 27236.036473892676}

In [103]:
best_tree_size_plus = min(scores_plus, key=scores_plus.get)
print("best_tree_size_plus: {:,.0f}\nmax_leaf_nodes_plus: {:,.0f}".format(best_tree_size_plus, scores_plus[best_tree_size_plus]))

best_tree_size_plus: 71
max_leaf_nodes_plus: 26,704

In [104]:
final_model = DecisionTreeRegressor(max_leaf_nodes=best_tree_size_plus, random_state=1)
final_model.fit(X, y)

DecisionTreeRegressor(max_leaf_nodes=71, random_state=1)

In [105]:
final_predictions = final_model.predict(X)
final_mae = mean_absolute_error(y, final_predictions)
final_mae

18692.256244288554

In [106]:
print("Predictions:", final_predictions[:5].tolist())
print("Prices:", y.head().tolist())

Predictions: [200687.5, 146415.007518797, 200687.5, 163719.12121212122, 291893.1818181818]
Prices: [208500, 181500, 223500, 140000, 250000]